dist: trusty
language: rust
rust: nightly
services: docker
sudo: required

matrix:
    include:
        - os: linux
          env: TARGET=x86_64-unknown-linux-gnu
        - os: osx
          env: TARGET=x86_64-apple-darwin

before_install: ci/before_install.sh
script: ci/build.sh
